spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.plf.stream.mapper: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.plf.stream.pojo
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0