# 数据库的配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# pageHelper的配置
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: false
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  supportMethodsArguments: false
  helper-dialect: mysql

# mybatis配置
# 实体类扫描
mybatis:
  type-aliases-package: com.plf.boot.plugin.bean
  configuration:
    # 开启驼峰
    map-underscore-to-camel-case: true
  config:
    sql-with-param: true
# 配置映射文件位置
#mybatis.mapper-locations=classpath:/mapper/*.xml
