server:
  port: 8002


feign:
  httpclient:
    enabled: true
  client:
    config:
      ## default 设置的全局超时时间，指定服务名称可以设置单个服务的超时时间
      default:
        connectTimeout: 3000
        readTimeout: 3000

logging:
  level:
    root: info
    com.plf.feign.client.service: debug